"""
Script for aggregating and preparing the sequential weather table
and processing the fire size distribution table.
"""

import argparse
import logging
from pathlib import Path

import pandas as pd

from data_preparation.feature_processing.weather import load_weather_list, preprocess_weather_list
from data_preparation.utils import aggregate_csv_by_pattern, find_file_path, process_fire_size_df

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")


def build_weather_table(root_dir: Path, save_path: Path, pattern: str = "hex*/tabular/hex*_DailyWeather.csv"):
    """
    Aggregates weather CSVs into a single table and applies global preprocessing.
    Args:
        root_dir (Path): Root directory to search for weather CSV files.
        save_path (Path): Path to save the aggregated and processed weather table.
        pattern (str): Glob pattern to match weather CSV files.
    """
    df_weather = aggregate_csv_by_pattern(root_dir=root_dir, pattern=pattern, load_function=load_weather_list)
    # Apply weather specific global normalization
    df_weather = preprocess_weather_list(df_weather)
    df_weather.to_csv(save_path, index=False)
    logger.info(f"Aggregated weather data saved to {save_path} with shape {df_weather.shape} and columns: {df_weather.columns.tolist()}")


def process_fire_size_distribution_table(input_path: Path, output_path: Path):
    """
    Processes the fire size distribution table.
    Args:
        input_path (Path): Path to the existing fire size distribution CSV file.
        output_path (Path): Path to save the processed fire size distribution CSV file.
    """
    df_fire_size = pd.read_csv(input_path)
    df_fire_size_processed = process_fire_size_df(df_fire_size)
    df_fire_size_processed.to_csv(output_path, index=False)
    logger.info(
        f"Processed fire size distribution data saved to {output_path} with shape {df_fire_size_processed.shape} and columns: {df_fire_size_processed.columns.tolist()}"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Compile raw weather CSVs into a single lookup table and processing fire size distribution table."
    )
    parser.add_argument("--root_dir", type=str, required=True, help="Path to raw data root directory")
    parser.add_argument("--save_dir", type=str, required=True, help="Path to save directory")
    parser.add_argument(
        "--weather_output_file",
        type=str,
        help="File name (ends in .csv) to be used to save the aggregated and processed weather table",
        default="weather_table.csv",
    )
    parser.add_argument(
        "--fire_size_input_file",
        type=str,
        help="File name (ends in .csv) of existing fire size distribution table",
        default="df_fire_fru.csv",
    )
    parser.add_argument(
        "--fire_size_output_file",
        type=str,
        help="File name (ends in .csv) to be used to save the processed distribution table",
        default="df_fire_fru_processed.csv",
    )

    args = parser.parse_args()
    root_dir = Path(args.root_dir)
    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    weather_save_path = save_dir / args.weather_output_file
    fire_size_save_path = save_dir / args.fire_size_output_file
    fire_size_read_path = find_file_path(
        args.fire_size_input_file, root_dir, save_dir
    )  # Allows for flexibility in where the fire size distribution file is located, since it was generated by Yan and saved in the data_sampling_approach_XYZ folder and I don't want to assume it's in the sampling folder or the raw data folder. It will look in both and use the one it finds first.

    build_weather_table(root_dir=root_dir, save_path=weather_save_path)
    process_fire_size_distribution_table(input_path=fire_size_read_path, output_path=fire_size_save_path)


if __name__ == "__main__":
    main()
