# Where to save checkpoints
save_dir: "experiments/unet_run_001_approach_2"

#Base dir for all the hexel data
base_dir: "../yan_bp3"

# approaches 1 or 2
modelling_approach: "2"

seed: 42
deterministic: True

model:
  input_channels: 3 # if using one hot encoding, we add more 14 more features
  num_classes: 1

optimizer:
  name: "AdamW" # "SGD", "Adam", "AdamW"
  lr: 1.0e-3
  loss_name: "mae" # mse, bce, mae, etc

training:
  max_epochs: 20
  # Logging frequency in epochs
  log_every_n_epoch: 1

data:
  root_dir: "../yan_bp3/data_samples_approach_2"
  raw_data_dir: "../yan_bp3"

  train_split: "train_indices.csv"
  val_split: "val_indices.csv"
  test_split: "test_indices.csv"

  batch_size: 64
  num_workers: 2

  output_normalization: "min_max"

  feature_names_list: ["ignition_grid", "fuel_grid", "elevation_grid"] # ["ignition_grid", "esc_fires_grid", "fuel_grid", "elevation_grid", "weather_grid", "wind_grid"]
  fuel_feats_encoding: "ordinal" # ordinal, one_hot
  normalize_fuel_feats_ordinal: True
  valid_mask_threshold:  0.00

logger:
  enabled: True
  project_name: "nrcan-wildfireriskmapping"
  workspace: "mila-amlrt"
  experiment_name: "unet_run_001_approach_2"
  tags: ["baseline", "first-exp", "modelling_approach=2", "sigmoid+mse_loss", "3inputfeatures", "standardized_probs", "masked_metrics"]
  # log loss and metrics on comet every n steps
  log_every_n_step: 5

metrics: ["mse", "mae", "spearman", "ssim"]
