# Where to save checkpoints
save_dir: "experiments/unet_run_001_approach_2"

#Base dir for all the hexel data
base_dir: "../yan_bp3"

# approaches 1 or 2
modelling_approach: "2"

seed: 42
deterministic: True

model:
  num_classes: 1

optimizer:
  name: "AdamW" # "SGD", "Adam", "AdamW"
  lr: 1.0e-3
  loss: "kl" # mse, bce, mae, etc

training:
  max_epochs: 20
  # Logging frequency in epochs
  log_every_n_epoch: 1

evaluation:
  best_ckpt_metrics: ["spearman", "ssim"] # loss, ssim, mae, etc
  best_ckpt_metrics_mode: ["max", "max"] # max, or min
  checkpoint_filename: "best.pth" # option to load best or last

data:
  root_dir: "../burnp3plus/data_samples_approach_2"
  raw_data_dir: "../burnp3plus"

  train_split: "train_indices.csv"
  val_split: "val_indices.csv"
  test_split: "test_indices.csv"

  transforms_list: [] # options: "random_flip", "random_rotate"
  augmentation_prob: 0.0 # float between 0 and 1

  batch_size: 64
  num_workers: 2

  output_normalization: "min_max" #log

  feature_names_list: ["ignition_grid", "fuel_grid", "elevation_grid"] # ["ignition_grid", "esc_fires_grid", "fuel_grid", "elevation_grid", "weather_grid", "wind_grid"]
  fuel_feats_encoding: "one_hot" # ordinal, one_hot
  normalize_fuel_feats_ordinal: True
  valid_mask_threshold:  0.00

  input_sources:
    - name: "grid"
      params:
        feature_names_list: ["ignition_grid", "fuel_grid", "elevation_grid"]
        target_name: "bp"
        out_norm: "min_max"
        fuel_feats_encoding: "one_hot"
        normalize_fuel_feats_ordinal: True
        transforms_list: []
        augmentation_prob: 0.0

logger:
  enabled: True
  project_name: "nrcan05-wildfireriskmapping"
  workspace: "mila-amlrt"
  experiment_name: "unet_run_001_approach_2"
  tags: ["baseline", "first-exp", "modelling_approach=2", "fuel_one_hot_encoding", "KL-loss", "3inputfeatures", "standardized_probs", "masked_metrics"]
  # log loss and metrics on comet every n steps
  log_every_n_step: 10

metrics: ["mse", "mae", "normalized_mae", "spearman", "bias", "ccc", "kl_div", "iou_top005", "iou_top01", "iou_top02", "iou_top05", "iou_top10", "auc_iou_top10", "auc_iou_full"]
