# Where to save checkpoints
save_dir: "experiments/unet_full_data_spatial_weather"

# approaches 1 or 2
modelling_approach: "1"

seed: 42
deterministic: True

model:
  num_classes: 1
  input_feature_list: ["spatial", "auxillary"]

  auxillary_hidden_dims:
    weather: [32, 64]

  auxillary_embed_dims:
    weather: 128

  auxillary_poolings:
    weather: "max" # max, mean, attention

optimizer:
  name: "AdamW" # "SGD", "Adam", "AdamW"
  lr: 1.0e-3
  loss: "kl" # or ["bce", "kl"], str for single loss or list for multiple weighted losses
  # loss_weights: {"bce": 0.8, "kl": 0.2} # use if loss is a list

training:
  max_epochs: 50
  # Logging frequency in epochs
  log_every_n_epoch: 1

evaluation:
  best_ckpt_metrics: ["spearman"] # loss, ssim, mae, etc
  best_ckpt_metrics_mode: ["max"] # max, or min
  checkpoint_filename: "best.pth" # option to load best or last

data:
  root_dir: "/network/projects/amlrt/nrcan_wildfires/full_data/yan_bp3/data_samples_approach_1_weather"
  raw_data_dir: "/network/projects/amlrt/nrcan_wildfires/full_data/yan_bp3"

  train_split: "train_indices.csv"
  val_split: "val_indices.csv"
  test_split: "test_indices.csv"

  batch_size: 64
  num_workers: 2

  input_sources:
    - name: "grid"
      params:
        feature_names_list: ["ignition_grid", "fuel_grid", "elevation_grid"]
        out_norm: "min_max"
        fuel_feats_encoding: "one_hot"
        normalize_fuel_feats_ordinal: True
        transforms_list: []
        augmentation_prob: 0.0
    - name: "weather"
      params:
        csv_name: "weather_table.csv"
        feature_names_list: ["temp", "rh", "prec", "ffmc", "dmc", "dc", "isi", "bui"] # other options: "wd", "ws", "fwi"
        fire_weather_zone_id_col: "wx_zone"
        sampling_approach: "mode"
        num_samples_per_patch: 256
        transforms_list: []
        augmentation_prob: 0.0

logger:
  enabled: True
  project_name: "nrcan-wildfireriskmapping"
  workspace: "mila-amlrt"
  experiment_name: "unet_full_data_spatial_weather"
  tags: ["baseline", "full_data", "modelling_approach=1", "fuel_one_hot_encoding", "KL-loss", "3inputfeatures", "weather-tabular"]
  # log loss and metrics on comet every n steps
  log_every_n_step: 5

metrics: ["mse", "mae", "spearman", "ssim", "bias"]
