# Where to save checkpoints
save_dir: "checkpoints/unet_run_001"

model:
  input_channels: 20
  num_classes: 1

optimizer:
  lr: 1.0e-3

training:
  # Used by Trainer.run_training(...)
  max_epochs: 2
  # Logging frequency in epochs
  log_every_n_epoch: 1

logger:

metrics: