# Where to save checkpoints
save_dir: "experiments/unet_run_001_approach_1"

# approaches 1 or 2
modelling_approach: "1"

seed: 42
deterministic: True

model:
  num_classes: 1
  input_feature_list: ["spatial"]

optimizer:
  name: "AdamW" # "SGD", "Adam", "AdamW"
  lr: 1.0e-3
  loss: "kl" # or ["bce", "kl"], str for single loss or list for multiple weighted losses
  # loss_weights: {"bce": 0.8, "kl": 0.2} # use if loss is a list

lr_scheduler:
  name: null # options: "cosine_warmup", "plateau", "onecycle", "multistep" (or null)
  # warmup_epochs: 5 # if using cosine_warmup
  # max_lr: 1.0e-3 # if using onecycle
  # patience: 5 # if using plateau
  # factor: 0.1 # if using plateau or multistep
  # milestones: [30, 40] # if using multistep

training:
  max_epochs: 10
  # Logging frequency in epochs
  log_every_n_epoch: 1

evaluation:
  best_ckpt_metrics: ["spearman"] # loss, ssim, mae, etc
  best_ckpt_metrics_mode: ["max"] # max, or min
  checkpoint_filename: "best.pth" # option to load best or last

data:
  root_dir: "../yan_bp3/data_samples_approach_1"
  raw_data_dir: "../yan_bp3"

  train_split: "train_indices.csv"
  val_split: "val_indices.csv"
  test_split: "test_indices.csv"

  batch_size: 64
  num_workers: 2

  input_sources:
    - name: "grid"
      params:
        feature_names_list: ["ignition_grid", "fuel_grid", "elevation_grid"]
        out_norm: "min_max"
        fuel_feats_encoding: "one_hot"
        normalize_fuel_feats_ordinal: True
        transforms_list: []
        augmentation_prob: 0.0

logger:
  enabled: True
  project_name: "nrcan05-wildfireriskmapping"
  workspace: "mila-amlrt"
  experiment_name: "unet_run_001_approach_1"
  tags: ["baseline", "first-exp", "modelling_approach=1", "fuel_one_hot_encoding", "KL-loss", "3inputfeatures"]
  # log loss and metrics on comet every n steps
  log_every_n_step: 10

metrics: ["mse", "mae", "spearman", "bias", "ccc", "kl_div", "iou_top005", "iou_top01", "iou_top02", "iou_top05", "iou_top10", "auc_iou_top10", "auc_iou_full"]
